### ISSUE TITLE
Add support for geyser and floodgate

### ISSUE THREAD

**Issue by Giacomo213342** [MinecraftChannel/BungeeCord-BotFilter#2]
Hello, I have botfilter, but also bedrock players get flagged, so I'm here to ask the support of floodgate to make bedrock players bypass the fall test. Thanks!

**Comment by maythiwat** [comment]
Thanks for suggestion, but this is a forked version of BotFilter (A Russian Version released in rubukkit.org)
Many patches are hard-coded (especially bot-filtering features) 
They updating them by pulling from main Spigot repo then adding/replacing the code.

So i cannot easily patch that (some variables/message are hard-coded)
except they switched to use patching method like PaperMC does with Waterfall, that will be easier.

Maybe, you should ask the original author to do that instead.
since this forked project is abandoned (not updated for almost 2 years!) Sorry!!!

Here's link that should be useful for you.
**Original Russian Thread**
http://rubukkit.org/threads/antibot-botfilter-zaschiti-svoj-server-ot-botov-update-12-02-2021-1-8-1-16-5.137038/
**Original Russian Repo** https://github.com/Leymooo/BungeeCord
